spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/codingcompetition
    password: postgres
  jpa:
    properties:
      jdbc:
        timezone: UTC
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: 'true'
  mail:
    host: 'smtp.mailtrap.io'
    port: '25'
    username: '3c5c625c2ad413'
    password: '291ce18bd56deb'
    protocol: 'smtp'
  thymeleaf:
    prefix: 'classpath:/templates/'
    suffix: '.html'